### ISSUE TITLE
direction of effect estimates

### ISSUE THREAD

**Issue by Annefeng** [syntheke/bayesR#10]
Hi,

I'm running genomic prediction analysis using bayesR along with a few other methods. One thing I noticed is that BayesR seems to report effect sizes in opposite direction with the other models I ran. Specifically, BayesR reports effects for A2, but not A1. Can you help confirm if this is the correct understanding of the output? So that I can simply reverse the sign of the SNP weights.

Thanks!

**Comment by syntheke** [comment]
Hi,

can't speak for the other programs. Your understanding is correct, BayesR uses the major allele as reference, i.e PLINK binary genotypes coded as 0 (alt alt), 1 (alt ref) , 2 (ref ref).

Cheers

**Comment by Annefeng** [comment]
Thanks for the quick reply! 

A follow-up (though not-so-related) question:
I want to apply the BayesR SNP effect sizes trained in a discovery sample (plink best-guess genotype files) to an independent sample that has only dosage files. As BayesR currently does not handle dosage format, for the prediction analysis I am planning to simply use the PLINK --score option. But there's the scaling issue of effect estimates-- are genotypes centered and standardized to have mean zero and unit-variance in BayesR when estimating beta's (I assume this is the case but not entirely sure), so that to use plink --score one would need to first transform the beta's back to the orginal genotype scale using (ref) allele frequency?

**Comment by syntheke** [comment]
Hi,

I'm not familiar with the --scoring options in PLINK. The PLINK manual provides an example how to apply scoring with --lasso output, and estimates in lasso are centered and scaled as well. Maybe there is an option to provide a "freq" file to  get the scores on the desired scale. 

Cheers
