### ISSUE TITLE
Using -dfvara -3.0

### ISSUE THREAD

**Issue by espride** [syntheke/bayesR#11]
Hello, I am trying to specify the heritability of my trait when using BayesR. For my input I have entered:

> bayesRv2 -bfile bfile_name -vara 0.49 -dfvara -3.0 -out outfile_name

However, I receive the following error:  
Missing argumnet for :-dfvara           5
ERROR: Problem parsing the command line arguments

When I input -dfvara 3.0 it works, but the log file indicates 3.0 and not -3.0

Is there a way to resolve this issue?  Thank you for any help you can provide!

**Comment by syntheke** [comment]
fixed
