### ISSUE TITLE
fam file

### ISSUE THREAD

**Issue by rcheng** [syntheke/bayesR#16]
There seem to be two problems regarding the fam file
- error occurs if columns are tab delimited
- error occurs if a phenotype is loaded with -n [num] where num > 55; see below for an error

forrtl: severe (24): end-of-file during read, unit -5, file Internal List-Directed Read
Image              PC                Routine            Line        Source             
bayesR             0000000000432F0E  Unknown               Unknown  Unknown
bayesR             00000000004594BD  Unknown               Unknown  Unknown
bayesR             0000000000457C26  Unknown               Unknown  Unknown
bayesR             0000000000413E78  Unknown               Unknown  Unknown
bayesR             000000000042AE53  Unknown               Unknown  Unknown
bayesR             000000000040309E  Unknown               Unknown  Unknown
libc-2.17.so       00002B8555068555  __libc_start_main     Unknown  Unknown
bayesR             0000000000402FA9  Unknown               Unknown  Unknown

**Comment by syntheke** [comment]
Easy to fix.

1. Don't use tab
2. Split your traits over several runs

**Comment by rcheng** [comment]
Sure. 

I figured those out and made changes but it took me lots of time to debug. In addition, one may need to make copies of some data if files of the plink format are used and jobs are run in parallel.
