### ISSUE TITLE
allele frequency

### ISSUE THREAD

**Issue by bryceduclu** [syntheke/bayesR#17]
hi,
I tried BayesRv2, using the flat type input files, and noticed frequency of the "2" allele reported in the ".frq" file is not correct (see below)
  0.326044
  0.324882
  0.325784
  0.326069
  0.321921
  0.325860
  0.321845
  0.325358
  0.321918
  0.324215
  0.328116
  0.324279
  0.326674
  0.326469
...

while the correct frequency should be:
1
0
0
0.506483
0.780649
0.492503
0.870877
0.357338
0.142133
0.554992
0.532854
0.467058
0.800759
0.997883
...

would you have any thought on this issue?

**Comment by syntheke** [comment]
I run example 1 using flat files and all the results files are quite different from the output in the example. Obviously, the program does not give correct results when using flat files.  For now,  you should convert your genotypes  to plink binary format.

**Comment by bryceduclu** [comment]
In the covariate file, can I have 1 column for Age (continuous) followed by incident matrix for categorical fixed effect?

**Comment by syntheke** [comment]
Flat file input should now work in the basic version, but is not yet supported when using blocks of SNPs (bayesRv2). The '2' allele indicates the major allele. In your example you need to flip the genotype codes for SNPs 6,8, etc.
