### ISSUE TITLE
Format/Readme file issue

### ISSUE THREAD

**Issue by nicolazzie** [syntheke/bayesR#2]
Hi, 
first of all, thanks for your bayesR model.
I'm starting heavy testing on simulated (WGS) data... and I've encountered a couple of issues:

**1) Line 60:    write(21,903) 'SNP output ', snpout**
Format 903 for snpout is i8, whereas snpout is logical. When running the pgm I get: 

```
At line 60 of file bayesR.f90 (unit = 21, file = 'simout.log')
Fortran runtime error: Expected INTEGER for item 3 in formatted transfer, got LOGICAL
(a,t30,'= ',i8)
            ^
```

I've patched it locally by adding a new format and editing line 60 as below.
- In **line 60**: `write(21,909) 'SNP output ', snpout`
- (Inserted) **line 295**: `909 format(a,t30,'= ',l)`

**2) The readme file should be edited** 

The command line provided: 
`bayesR -bfile simdata -out simout -numit 10000 -burnin 5000 -seed 333`
does not work when running the example provided.
It should be changed to: 
`bayesR -bfile example/simle -out simout -numit 10000 -burnin 5000 -seed 333`

_simout.log_ file now looks like this:

```
Program BayesR
      Run started at 2015-01-30 09:34:47
Prefix for input files       : example/simle
Prefix for output files      : simout
Phenotype column             =        1
No. of loci                  =    20000
No. of individuals           =     1000
No. of training individuals  =     1000
Prior Vara                   =   0.010000 -2.000000
Prior Vare                   =   0.010000 -2.000000
Model size                   =        0
No. of cycles                =      100
Burnin                       =       50
Thinning rate                =       10
No. of mixtures              =        4
Variance of dist             =    0.00000   0.00010   0.00100   0.01000
Dirichlet prior              =    1.00000   1.00000   1.00000   1.00000
Seed                         =      333
SNP output                   = F
```

Again, thank you for your work. We will be testing it intensively in the next few weeks.
Best regards,
E. Nicolazzi

**Comment by syntheke** [comment]
Hi Ezequiel

Thanks for spotting this, I will look into it.
THE code we put in the public domain is an last hour re-write to make the programs more user friendly. Most likely there will be a few more mistakes.


Cheers

Gerhard



--
Gerhard Moser
The University of Queensland
Queensland Brain Institute (QBI)
QBI Building (#79)
St Lucia, QLD 4072
Australia
Phone: +61 7 3346 6429
