### ISSUE TITLE
Issue to compile bayesR

### ISSUE THREAD

**Issue by benhedan** [syntheke/bayesR#20]
Hi

I  installed  bayesR with the following command :

```
git clone https://github.com/syntheke/bayesR.git
```

I installed gfortran with:

```
brew gcc
```

and when I tried to compile in src folder , I get this issue :

```
~/bayesR/src$ gfortran –o ../binary/bayesR –O2 -cpp RandomDistributions.f90 baymods.f90 bayesR.f90
ld: file not found: –o
collect2: error: ld returned 1 exit status
```

Could you help me on that?

Thank you

**Comment by syntheke** [comment]
Never tested bayesR on a MAC.   You can try typing the command, copying  text out of a PDF can  end up mangled in a variety of ways.

**Comment by syntheke** [comment]
Guilty myself. Formatted dash/hyphen in README

**Comment by benhedan** [comment]
Thank you

I have no the following issue :

gfortran -o bayesRv2 -O2 -cpp –Dblock -fopenmp RandomDistributions.f90 baymods.f90 bayesR.f90
ld: file not found: –Dblock
collect2: error: ld returned 1 exit status

Could you help me on this?

Best regards

Benoit

**Comment by benhedan** [comment]
Sorry and Thanks
