### ISSUE TITLE
Problem with user specification of negative values for the degrees of freedom Va (-dfvara) 

### ISSUE THREAD

**Issue by vincentgarin** [syntheke/bayesR#21]
I tried to manually specified the prior variance of the SNP effect (-dfvara) but I get an error. For positive values it works

Example code

./bayesR -bfile d -out res -dfvara -2.0 (default value)
./bayesR -bfile d -out res -dfvara -3.0

Error message

Missing argument for :-dfvara           5
STOP ERROR: Problem parsing the command line arguments

Thanks in advance for your help.

**Comment by syntheke** [comment]
Hmm,
I can see that  this was already fixed several years ago. Somehow it got lost when the previous two code bases were merged into one. Should work now.
