### ISSUE TITLE
bayesR performance problem

### ISSUE THREAD

**Issue by cron-weasley** [syntheke/bayesR#22]
Dear Auth,
When I build bayesR with intel parallel studio 2020 upfate4 ifort:
ifort -o bayesR_ifort -O3 -axCORE-AVX512 -fpp RandomDistributions.f90 baymods.f90 bayesR.f90
Then I run the example1 as command:
./bayesRv2_ifort -bfile simdata -out simout -numit 10000 -burnin 5000 -seed 333 -nthreads 28
The total command run about more than 16 minutes.
I check your example that your simout.log, only run for more than 1 mintues.
Then I use "strace ./bayesRv2_ifort -bfile simdata -out simout -numit 10000 -burnin 5000 -seed 333 -nthreads 28"
I found at last lots of sched_yield() and the process wait and wait.
So my question is:
First, Is there any errors of my operations?
Second, in example1, what is your test server environment, such as os version, gcc/ifort version， build command etc.

Thanks a lot!

**Comment by syntheke** [comment]
Have you tried to compile as it is shown in README?

ifort -o bayesR -O3 -fpp RandomDistributions.f90 baymods.f90 bayesR.f90
ifort -o bayesRv2 -O3 -fpp -Dblock -openmp -static RandomDistributions.f90 baymods.f90 bayesR.f90

The first line compiles the 'one processor' binary, the second the parallel version bayesRv2.

I'm not familiar with the newer Fortran compilers.  However, I'm missing the -D flag for the preprocessor in your command. Without the -openmp flag (or something similar) how does the compiler create code that runs on multiple cores/threads?

**Comment by cron-weasley** [comment]
> Have you tried to compile as it is shown in README?
> 
> ifort -o bayesR -O3 -fpp RandomDistributions.f90 baymods.f90 bayesR.f90 ifort -o bayesRv2 -O3 -fpp -Dblock -openmp -static RandomDistributions.f90 baymods.f90 bayesR.f90

Answer: Yes, I compile the code follow the readme, but the performance is low, then I change the compile flags as I write here.

> 
> The first line compiles the 'one processor' binary, the second the parallel version bayesRv2.

Answer: sorry, I forget to write the bayesRv2 command:
ifort -o bayesRv2_ifort -O3 -xCORE-AVX2 -fpp -Dblock -qopenmp RandomDistributions.f90 baymods.f90 bayesR.f90
here is the bayesRv2 build command.

> 
> I'm not familiar with the newer Fortran compilers. However, I'm missing the -D flag for the preprocessor in your command. Without the -openmp flag (or something similar) how does the compiler create code that runs on multiple cores/threads?

Thanks a lot for your quickly reply syntheke!

**Comment by syntheke** [comment]
Is the performance slow when you run the command without the -nthread flag? I haven't come across a problem where the default value of 4 was not optimal.

**Comment by cron-weasley** [comment]
> Is the performance slow when you run the command without the -nthread flag? I haven't come across a problem where the default value of 4 was not optimal.

Thanks a lot! And I will try later. And what is your build environment setting?  I mean OS version gcc/icc version of you.

**Comment by cron-weasley** [comment]
> Is the performance slow when you run the command without the -nthread flag? I haven't come across a problem where the default value of 4 was not optimal.

I test with -nthread with different number, time result of example1 test case is:

nthreads 96 : 37min58sec
nthreads 24 : 13min38sec
nthreads 4 : 6min9sec

My Server is 4*Intel Xeon 6448H，with 128 pyhsical cores（bios disable Hyperthread）

**Comment by syntheke** [comment]
What information of the time command are you reporting, real/user/sys?  

Below are the outputs running bayesR on my loptop with a single Intel i7 CPU @ 1.30GHz.   

**bayesR -bfile simdata -out simout -numit 10000 -burnin 5000 -seed 333**
real	1m53.077s
user	1m52.994s

**bayesRv2 -bfile simdata -out simout -numit 10000 -burnin 5000 -seed 333**
real	3m36.941s
user	14m25.960s

**Comment by cron-weasley** [comment]
> Is the performance slow when you run the command without the -nthread flag? I haven't come across a problem where the default value of 4 was not optimal.

Here the picture show for you：
<img width="1461" alt="e195b69b91f189d7ae29c13bc696a07" src="https://github.com/syntheke/bayesR/assets/6168425/586f9faf-c0c6-4311-ab12-67c8fb7f43a7">

**Comment by syntheke** [comment]
The example data provided only contain a small number of markers and individuals and are not appropriate to test the performance of the bayesRv2. I can't help you with issues that seem to be specific to your compute environment.

Cheers

**Comment by cron-weasley** [comment]
> The example data provided only contain a small number of markers and individuals and are not appropriate to test the performance of the bayesRv2. I can't help you with issues that seem to be specific to your compute environment.
> 
> Cheers

Got it, Thanks a lot~~~
