### ISSUE TITLE
How do I run BayesR with large memory ?

### ISSUE THREAD

**Issue by Feng-Zhang** [syntheke/bayesR#4]
I want to run BayesR with 428895 SNPs and 7621, but how can I give 120G memory to BayesR to save run time? Adding number of threads did not work. Following is my pbs script:
````
#!/bin/bash
#PBS -S /bin/bash
#PBS -N bayesR_1_1
#PBS -l walltime=40:00:00
#PBS -l procs=32
#PBS -l mem=200000mb

workDir=/home/fz4/gp/bayesR/HD/mutipleBreed
bayesRv2=/home/fz4/bin/exeSofts/bayesRv2

cd $workDir
$bayesRv2 -bfile adjADG_HD_train_breed1_cv1 -out adjADG_HD_train_breed1_cv1 -nthreads 32
````

Any tips and suggestions will be greatly appreciated.

**Comment by syntheke** [comment]
Hi Feng-Zhang,

sorry for the late reply, but I was out of town for the last couple of weeks.

The program tries to allocate the memory it requires. If there is not enough memory available it will  stop with an error message. Providing extra memory than what is required does NOT speed up the program.  

BayesRv2 has limited hardcoded parallelisation and using 32 cores will result in a lot of overhead and this may increase run time considerably.

I don't know PBS very, well, but I think the procs parameter is required for distributed-memory clusters.
Have you tried to run the program on a single node requesting 4 cores? On my system this would look like 'qsub -l nodes=1:ppn=4,mem=30gb,walltime=40:00:00

Cheers
