### ISSUE TITLE
How to adjust the proportion of SNPs with no additive effect ?

### ISSUE THREAD

**Issue by Feng-Zhang** [syntheke/bayesR#5]
1. After running BayesR with default parameters, the proportion of SNPs from 4 distribution (variance equals 0,0.0001,0.001,0.01) approximately are 0.84, 0.15, 0.005, 0.0006, respectively. 
   But I want to compare the difference of prediction using BayesR and BayesB, so when running BayesR, the proportion of SNPs with 0 varience should be set as **0.95**, as same as π using BayesB. 
2. “-delta 2” sets the prior to 2 for all mixture components. But what exactly is the parameter meaning?  If the number is larger, how does it affect the result of genomic prodiction?

Could you please tell me how to set the proportion? Any suggestions or tips would be greatly appreciated.

**Comment by syntheke** [comment]
In BayesB each SNP has its own variance and such models are not implemented in BayesR. 
Check out the chapter by Fernando and Garrick in "Genome-Wide Association Studies and Genomic Prediction" for R code of BayesB.

**Comment by Feng-Zhang** [comment]
In BayesR 84% of SNPs has variance 0 from the result I ran and 95% of SNPs has no effect in BayesB. What is the difference I did not notice?   
I just want to adjust the proportion of SNPs with no effect, so that the two model are comparable.

**Comment by GabrieleNocchi** [comment]
This was a good question: 
The parameter "delta", prior for Dirichlet , affect the proportion of SNPs effect. But I am not sure the prior inforatmtin can affect the final result ? Or do not affect the reuslt but only the convergence speed?

It would be nice to know more.
