### ISSUE TITLE
Shape parameter must be positive

### ISSUE THREAD

**Issue by bmlett** [syntheke/bayesR#7]
Hello- 

I am running the BayesR with the default parameters. As it runs it prints out the above message "Shape parameter must be positive" and I am wondering what this is referring to in regards to the input files? 

Thanks

**Comment by syntheke** [comment]
Hi

"Shape parameter must be positive"  refers to the shape of the gamma distribution. The gamma is used to generate draws from the inverted-chi-squared distribution.  This can happen when either the current model does not include more than two SNPs or when there are too few records in the data. Try to set _dfvara_ and _dfvare_ to a number > 2 to force the scale to be positive.

Cheers
